<?php
$options = array(
    // Enable Image Mode
    array(
        'id' => 'layout_style',
        'type' => 'button_set',
        'title' => esc_html__('Layout Style', 'epcl_framework'),
        'desc' => esc_html__('Display text only or enable images on Post Lists.', 'epcl_framework'),
        'options'  => array(
            'image' => esc_html__('Image (if available)', 'epcl_framework'),
            'text' => esc_html__('Text Only', 'epcl_framework'),             
        ),
        'default' => 'text',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar'),
    ),
    // ALl Posts Lists
    array (
        'id' => 'module_title',
        'title' => esc_html__('Module Title', 'epcl_framework'),
        'subtitle' => esc_html__('e.g. Latest Articles', 'epcl_framework'),
        'desc' => esc_html__('Leavy empty to remove.', 'epcl_framework'),
        'type' => 'text',
        'default' => 'Latest Articles',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar,posts_carousel,popular_categories'),   
    ),
    array (
        'id' => 'orderby',
        'title' => esc_html__('Order by (optional)', 'epcl_framework'),
        'subtitle' => esc_html__('Default: By Date', 'epcl_framework'),
        'type' => 'select',
        'options' => array(
            'date' => esc_html__('By Date (recent posts)', 'epcl_framework'),
            'views' => esc_html__('By Post Views (popular posts)', 'epcl_framework'),
            'title' => esc_html__('By Name', 'epcl_framework'),
        ),
        'default' => 'date',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar,posts_carousel'),   
    ),
    array (
        'id' => 'date',
        'title' => esc_html__('Date (optional)', 'epcl_framework'),
        'subtitle' => esc_html__('Default: All Time', 'epcl_framework'),
        'desc' => esc_html__('Combine with order by Post Views to get your popular posts.', 'epcl_framework'),
        'type' => 'select',
        'options' => array(
            'alltime' => esc_html__('All Time', 'epcl_framework'),
            'pastyear' => esc_html__('Past Year', 'epcl_framework'),
            'pastmonth' => esc_html__('Past Month', 'epcl_framework'),
            'pastweek' => esc_html__('Past Week', 'epcl_framework'),
        ),
        'default' => 'alltime',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar,posts_carousel'),
    ),
    array (
        'id' => 'posts_order',
        'title' => esc_html__('Order (optional)', 'epcl_framework'),
        'subtitle' => esc_html__('Default: DESC', 'epcl_framework'),
        'desc' => esc_html__('Default descending (highest to lowest value).', 'epcl_framework'),
        'type' => 'select',
        'options' => array(
            'ASC' => esc_html__('ASC (ascending)', 'epcl_framework'),
            'DESC' => esc_html__('DESC (descending)', 'epcl_framework'),
        ),
        'default' => 'DESC',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar,posts_carousel'), 
    ),
    array (
        'id' => 'offset',
        'title' => esc_html__('Offset (optional)', 'epcl_framework'),
        'subtitle' => esc_html__('Default: none', 'epcl_framework'),
        'type' => 'spinner',
        'desc' => esc_html__('This will exclude the first "X" posts from this module. Useful if you are using a slider/carousel with recent posts.', 'epcl_framework'),                    
        'min' => '0',                    
        'max' => '30',
        'step' => '1',
        'default' => '',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar'),   
    ),
    array(
        'id' => 'featured_categories',
        'title' => esc_html__('Featured Categories', 'epcl_framework'),                    
        'desc' => esc_html__('(Optional) select only post from these categories or leave blank to display all posts.', 'epcl_framework'),
        'type' => 'select',
        'chosen' => true,
        'multiple' => true,
        'sortable' => true,
        'options' => 'categories',
        'default' => '',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar,posts_slider,posts_carousel,categories_carousel,popular_categories'), 
    ),
    array(
        'id' => 'excluded_categories',
        'title' => esc_html__('Excluded Categories', 'epcl_framework'),
        'type' => 'select',
        'desc' => esc_html__('(Optional) Usefull if you dont want to display posts used on the carousel.', 'epcl_framework'),
        'chosen' => true,
        'multiple' => true,
        'sortable' => true,
        'options' => 'categories',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar,categories_carousel,popular_categories'), 
    ),
    array (
        'id' => 'grid_enable_masonry',
        'title' => esc_html__('Enable Masonry Style', 'epcl_framework'),
        'subtitle' => esc_html__('Recommended: ON', 'epcl_framework'),
        'desc' => esc_html__('You can display the posts like a normal grid or in masonry style.', 'epcl_framework'),
        'type' => 'switcher',
        'default' => true,
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar')
    ),
    array (
        'id' => 'enable_pagination',
        'title' => esc_html__('Display Pagination Button', 'epcl_framework'),
        // 'subtitle' => esc_html__('Recommended: ON', 'epcl_framework'),
        'desc' => esc_html__('Display the next/prev buttons and the pagination counter.', 'epcl_framework'),
        'type' => 'switcher',
        'default' => true,
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar'), 
    ),
    array(
        'id' => 'posts_per_page',
        'title' => esc_html__('Posts per page', 'epcl_framework'),
        'type' => 'spinner',
        'desc' => esc_html__('(Optional) by default is used the amount from Settings -> Reading option.', 'epcl_framework'),
        'min' => '2',
        'max' => '30',
        'step' => '1',
        'default' => '',
        'dependency' => array('layout', 'any', 'grid_posts,grid_sidebar,classic_posts,classic_posts_sidebar'), 
        // 'unit' => 'articles'
    ),
);

return $options;